### ISSUE TITLE
[BOTW] FPS++ causes game to freeze after resume from sleep on Steam Deck

### ISSUE THREAD

**Issue by yusefnapora** [ActualMandM/cemu_graphic_packs#570] opened 2022-10-04 15:29 UTC
**Describe the issue**

When playing BOTW on the Valve Steam Deck with FPS++ enabled, resuming from a suspended state causes the game to freeze. The game resumes normally if FPS++ is disabled, but of course its not as smooth and awesome.

**To Reproduce**
1. Boot game up on a Steam Deck with FPS++ enabled
2. Suspend the deck with the power button and resume it
3. The game state freezes, although some controller inputs will still cause sound effects, and the onscreen HUD switches to show the "arrow selection" UI if you hold ZR.

**Expected behavior**
The game resumes from sleep normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: SteamOS Holo v3.3.1
 - GPU: AMD
 - Renderer: Vulcan
 - Version: Tested against CEMU 1.27.1 via Proton (installed using Emudeck) and a native linux build of CEMU 2.0 (built using [these instructions](https://github.com/cemu-project/Cemu/issues/281)). 

 Not sure of the FPS++ version - it was downloaded via the "community graphics packs" button in both CEMU installs, so presumably it's the latest.

**Additional context**

I tried fiddling about with the various "fence" options and Static vs Dynamic in the advanced options, but to no avail.

**Comment by susejmaak** [comment] 2022-10-20 22:14
up please

**Comment by MAK0226** [comment] 2022-10-24 01:06
+1 on this. It's quite inconvenient.

**Comment by Crementif** [comment] 2022-10-24 08:55
I reproduced this a while ago when the Steam Deck first launched without any graphic packs. Are you sure this isn't a Cemu issue?

**Comment by MAK0226** [comment] 2022-10-24 14:10
> I reproduced this a while ago when the Steam Deck first launched without any graphic packs. Are you sure this isn't a Cemu issue?

It could be an issue with both FPS++ and Cemu. Wind Waker HD works perfectly without freezing.

**Comment by supasteb** [comment] 2022-10-24 18:17
Um, FPS++ works without a crash after sleep on steam deck with windows boot. I'm using the experimental version.

**Comment by MAK0226** [comment] 2022-10-24 18:32
> Um, FPS++ works without a crash after sleep on steam deck with windows boot. I'm using the experimental version. 

The issue is on SteamOS as mentioned.

**Comment by supasteb** [comment] 2022-10-24 18:43
> > Um, FPS++ works without a crash after sleep on steam deck with windows boot. I'm using the experimental version.
> 
> The issue is on SteamOS as mentioned.

Just letting peeps know if they want to go a different route.

**Comment by MAK0226** [comment] 2022-10-24 19:28
> > > Um, FPS++ works without a crash after sleep on steam deck with windows boot. I'm using the experimental version.
> 
> > 
> 
> > The issue is on SteamOS as mentioned.
> 
> 
> 
> Just letting peeps know if they want to go a different route. 

Good to know.

**Comment by MAK0226** [comment] 2022-11-14 03:13
This is fixed as of the SteamOS 3.4 Preview

**Closed** 2022-11-14 08:14 UTC
