### ISSUE TITLE
[Super Smash Bros. for Wii U] Black line at the bottom of screen with non-integer resolutions

### ISSUE THREAD

**Issue by auranticus** [ActualMandM/cemu_graphic_packs#347] opened 2019-03-24 08:56 UTC
The screen does not render properly when choosing 1280x720 or other non-integer resolutions - black line appears at the bottom of the screen
Take a look at the bottom of the screen (1280x720): https://i.imgur.com/nv1C7SX.png
When I choose other resolution (540p for example): https://i.imgur.com/g93dsGk.png

**Comment by slashiee** [comment] 2019-03-24 13:50
This is due to non-integer scaling. It may be possible to fix this in the same way as BotW where we manually add an extra pixel to specific textures.

**Comment by getdls** [comment] 2019-03-24 18:17
@windyboy1704  Try the latest commit, and see if that fixes the black line

**Comment by skalfate** [comment] 2019-03-24 21:28
I don't see the black bar anymore with my testing. I can confirm. Thanks getdls.

**Comment by windyboy1704** [comment] 2019-03-25 11:10
Fixed the black line at the bottom of the screen, but now it creates 2 small black lines at top and bottom, as if the game wasn't true 720p.
https://i.ibb.co/vsdKngy/Screenshot-193.png (don't know whether the link will be alive forever, Imgur compresses into JPG)

**Comment by getdls** [comment] 2019-03-25 11:16
Try setting aspect ratio to stretch

**Comment by windyboy1704** [comment] 2019-03-25 11:20
Stretch works, but why it has to? Other graphic packs work fine without setting to "stretch"
(Also it affects other resolutions)

**Comment by getdls** [comment] 2019-03-25 12:49
As slashie wrote, full fix requires shaders/ Cemu change, this is a workaround

**Comment by skalfate** [comment] 2019-03-25 23:53
The reason for the black lines at the top and bottom, is because the resolution presets are now being fed 1088p instead of 1080p as the games original height with that change posted above. What this does is, it affects aspect ratio very very lightly, which then differs from cemus default window which is set for 16/9.

When we have more time to spare, we'll take care of it. But for now it isn't that intrusive, right?

The statistics overlay gets affected similarly.

**Comment by slashiee** [comment] 2019-03-26 03:40
What could be done for now is having it be 1088 for the resolutions with the black lines

**Comment by Crementif** [comment] 2019-04-07 07:32
@slashiee is this now fixed by your https://github.com/slashiee/cemu_graphic_packs/commit/9440409e25697aedfc3bb622c08fd2e0a0ac18bd commit?

**Comment by slashiee** [comment] 2019-04-07 07:51
not for the 1280x720 resolution

**Comment by slashiee** [comment] 2020-11-23 03:31
For right now with the v6 pack I have removed the non-integer resolutions. I hope this gets fixed or worked around soon.

**Closed** 2021-01-28 00:37 UTC
Labels: resolution
